service:
  externalPort: 80
  internalPort: 80
ingress:
  tls:
    secretName: sam-ui-tls-secret
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "public"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"